#!/usr/bin/env python3
"""Rasterise the lying-down potato from assets/potato-look-v1.svg into the
e-paper portrait masks (firmware/paper/portrait.h).

    python3 firmware/tools/make_portrait.py > firmware/paper/portrait.h

Three 1-bit masks at 36x26 (body, underside shade, highlight), plus the two
face-eye centres and the small dimples, all in pixel coordinates. The firmware
combines the masks with a variety's dither at draw time; nothing here is tied
to a variety. No dependencies beyond the standard library.
"""
import re, sys

W, H = 36, 26
SS = 4  # supersamples per axis

# The #body path from the SVG, in the SVG's own units (centre-origin).
PATH = ("M -100,6 C -106,-38 -62,-74 -12,-72 C 38,-70 92,-56 104,-12 "
        "C 112,26 82,66 26,71 C -30,76 -94,54 -100,6 Z")
SHADE = (22, 44, 112, 62)      # cx, cy, rx, ry (clipped to body)
HILITE = (-42, -34, 58, 28)
EYES = [(-28, -14), (22, -17)]
DIMPLES = [(62, 22), (-62, 34), (30, 52), (-70, -20)]

def flatten(path, steps=24):
    nums = [float(t) for t in re.findall(r"-?\d+\.?\d*", path)]
    pts = [(nums[0], nums[1])]
    i = 2
    while i + 5 < len(nums):
        x0, y0 = pts[-1]
        x1, y1, x2, y2, x3, y3 = nums[i:i + 6]
        for s in range(1, steps + 1):
            t = s / steps
            a, b, c, d = (1 - t) ** 3, 3 * (1 - t) ** 2 * t, 3 * (1 - t) * t ** 2, t ** 3
            pts.append((a * x0 + b * x1 + c * x2 + d * x3, a * y0 + b * y1 + c * y2 + d * y3))
        i += 6
    return pts

poly = flatten(PATH)
xs = [p[0] for p in poly]; ys = [p[1] for p in poly]
minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
scale = min((W - 1) / (maxx - minx), (H - 1) / (maxy - miny))
ox = (W - (maxx - minx) * scale) / 2 - minx * scale
oy = (H - (maxy - miny) * scale) / 2 - miny * scale

def to_px(x, y):
    return x * scale + ox, y * scale + oy

def inside(poly, x, y):
    c = False
    n = len(poly)
    for i in range(n):
        x1, y1 = poly[i]; x2, y2 = poly[(i + 1) % n]
        if (y1 > y) != (y2 > y):
            xi = x1 + (y - y1) * (x2 - x1) / (y2 - y1)
            if x < xi: c = not c
    return c

def in_ellipse(e, x, y):
    cx, cy, rx, ry = e
    return ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2 <= 1.0

def mask(pred):
    rows = []
    for py in range(H):
        row = []
        for px in range(W):
            hits = 0
            for sy in range(SS):
                for sx in range(SS):
                    # pixel centre back into SVG units
                    x = (px + (sx + 0.5) / SS - ox) / scale
                    y = (py + (sy + 0.5) / SS - oy) / scale
                    if pred(x, y): hits += 1
            row.append(1 if hits * 2 >= SS * SS else 0)
        rows.append(row)
    return rows

body = mask(lambda x, y: inside(poly, x, y))
shade = mask(lambda x, y: inside(poly, x, y) and in_ellipse(SHADE, x, y))
hi = mask(lambda x, y: inside(poly, x, y) and in_ellipse(HILITE, x, y))

def emit(name, rows):
    print("static const uint8_t %s[PORTRAIT_H][PORTRAIT_STRIDE] = {" % name)
    for row in rows:
        bytes_ = []
        for b in range((W + 7) // 8):
            v = 0
            for bit in range(8):
                x = b * 8 + bit
                if x < W and row[x]: v |= 0x80 >> bit
            bytes_.append("0x%02X" % v)
        print("    {%s}," % ", ".join(bytes_))
    print("};")

print("#pragma once")
print("#include <stdint.h>")
print("// Generated by firmware/tools/make_portrait.py from assets/potato-look-v1.svg.")
print("// The lying-down potato at %dx%d: body, underside shade and highlight masks" % (W, H))
print("// (MSB first, %d bytes per row). Eyes and dimples are centres in pixels." % ((W + 7) // 8))
print("#define PORTRAIT_W %d" % W)
print("#define PORTRAIT_H %d" % H)
print("#define PORTRAIT_STRIDE %d" % ((W + 7) // 8))
emit("PORTRAIT_BODY", body)
emit("PORTRAIT_SHADE", shade)
emit("PORTRAIT_HI", hi)
print("static const int8_t PORTRAIT_EYES[2][2] = {%s};" % ", ".join(
    "{%d, %d}" % tuple(round(v) for v in to_px(*e)) for e in EYES))
print("static const int8_t PORTRAIT_DIMPLES[%d][2] = {%s};" % (len(DIMPLES), ", ".join(
    "{%d, %d}" % tuple(round(v) for v in to_px(*d)) for d in DIMPLES)))
for row in body:
    sys.stderr.write("".join("#" if v else "." for v in row) + "\n")
